version: "2"
plugins:
  pep8:
    enabled: true
  bandit:
    enabled: true
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  radon:
    enabled: true
  shellcheck:
    enabled: true
  sonar-python:
    enabled: true
    config:
      tests_patterns:
        - "**/test_*"
      # Possible values are: info, minor, major (default), critical, blocker
      minimum_severity: major
exclude_patterns:
  - "**/test_*"
